name: classroom
description: "A new Flutter project."
publish_to: "none"
version: 0.0.1

environment:
  sdk: ">=3.2.5 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  firebase_core: ^4.2.0
  flutter_screenutil: ^5.9.3
  firebase_messaging: ^16.0.1
  firebase_analytics: ^12.0.1
  haptic_feedback: ^0.5.1+1
  hive_flutter: ^1.1.0
  json_annotation: ^4.9.0
  shared_preferences: ^2.5.3
  cupertino_icons: ^1.0.8
  dio: ^5.9.0
  go_router: ^16.2.1
  device_preview: ^1.3.1
  flutter_riverpod: ^3.0.3
  flutter_local_notifications: ^19.4.2
  flutter_dotenv: ^6.0.0
  flutter_localizations:
    sdk: flutter
  intl: ^0.20.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  build_runner: ^2.7.1
  json_serializable: ^6.11.1
  change_app_package_name: ^1.5.0
  flutter_launcher_icons: ^0.14.4

flutter:
  uses-material-design: true
  generate: true

  assets:
    - .env
