// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCw7g1uOvUaeKI5YW8olS86axgM5V3B8hg',
    appId: '1:511476429277:web:83daa82ba5eba9afda0634',
    messagingSenderId: '511476429277',
    projectId: 'classroom-c88cc',
    authDomain: 'classroom-c88cc.firebaseapp.com',
    storageBucket: 'classroom-c88cc.firebasestorage.app',
    measurementId: 'G-RT8ENJJ3Z6',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC7wb4YGgoYpY2QCnMB01HCU4b9c3bKzAo',
    appId: '1:511476429277:android:15792dfe7f6a5f24da0634',
    messagingSenderId: '511476429277',
    projectId: 'classroom-c88cc',
    storageBucket: 'classroom-c88cc.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCeEoFEcP0iqjBJ6hy6CE2oO47Q69O1nsM',
    appId: '1:511476429277:ios:9f4c5afdec31945bda0634',
    messagingSenderId: '511476429277',
    projectId: 'classroom-c88cc',
    storageBucket: 'classroom-c88cc.firebasestorage.app',
    iosBundleId: 'com.example.classroom',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCeEoFEcP0iqjBJ6hy6CE2oO47Q69O1nsM',
    appId: '1:511476429277:ios:9f4c5afdec31945bda0634',
    messagingSenderId: '511476429277',
    projectId: 'classroom-c88cc',
    storageBucket: 'classroom-c88cc.firebasestorage.app',
    iosBundleId: 'com.example.classroom',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCw7g1uOvUaeKI5YW8olS86axgM5V3B8hg',
    appId: '1:511476429277:web:30ccb3fcfa4e1a6bda0634',
    messagingSenderId: '511476429277',
    projectId: 'classroom-c88cc',
    authDomain: 'classroom-c88cc.firebaseapp.com',
    storageBucket: 'classroom-c88cc.firebasestorage.app',
    measurementId: 'G-JWW2TN0F8M',
  );
}
